name: armTemplateDeplyment
on:
  workflow_dispatch:


jobs:
  armDeploy:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4your
      - name: Azure Login
        uses: Azure/login@vs2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
